### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AlexNazW** [Interfacelab/ilab-media-tools#103]
**Describe the bug**
Hello, i see this when try to active plugin. What it that, can you help please?

Fatal error: Uncaught Error: Call to undefined function ILABAmazon\manifest() in **plugins/ilab-media-tools/vendor/ilab/ilab-aws-media-cloud-sdk/src/AwsClient.php:170 Stack trace: #0 **plugins/ilab-media-tools/vendor/ilab/ilab-aws-media-cloud-sdk/src/S3/S3Client.php(283): ILABAmazon\AwsClient->__construct(Array) #1 **plugins/ilab-media-tools/classes/Storage/Driver/S3/S3Storage.php(491): ILABAmazon\S3\S3Client->__construct(Array) #2 **plugins/ilab-media-tools/classes/Storage/Driver/S3/S3Storage.php(510): ILAB\MediaCloud\Storage\Driver\S3\S3Storage->getS3Client(‘us-east-1’, NULL) #3 **plugins/ilab-media-tools/classes/Storage/Driver/S3/S3Storage.php(160): ILAB\MediaCloud\Storage\Driver\S3\S3Storage->getClient(NULL) #4 /s in **plugins/ilab-media-tools/vendor/ilab/ilab-aws-media-cloud-sdk/src/AwsClient.php on line 170

**How did you install the plugin?**
Did you install via composer, a git checkout, wordpress.org, freemius?

**Additional context**

**Comment by AlexNazW** [comment]
write code better next time.

**Comment by jawngee** [comment]
Says the guy using FTP in 2019
