### ISSUE TITLE
Call to undefined function imagecreatefromstring()

### ISSUE THREAD

**Issue by cenobitedk** [Interfacelab/ilab-media-tools#107]
**Describe the bug**
I have installed the latest version of the plugin but when I try to upload a picture it fails with an error message, see screenshot and log.

**To Reproduce**
1. Go to 'Media.'
2. Click on 'Select file' and select file
3. Wait...

**Expected behavior**
Expected upload to succeed.

**Screenshots**
<img width="810" alt="Screenshot 2020-03-07 at 10 53 45" src="https://user-images.githubusercontent.com/1397207/76141167-f7943180-6061-11ea-8fb9-050eac99390f.png">

```
[07-Mar-2020 09:50:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefromstring() in /app/web/wp/wp-includes/class-wp-image-editor-gd.php:96
Stack trace:
#0 /app/web/app/plugins/ilab-media-tools/classes/Tools/Storage/StorageImageEditor.php(98): WP_Image_Editor_GD->load()
#1 /app/web/wp/wp-includes/media.php(3189): ILAB\MediaCloud\Tools\Storage\StorageImageEditor->load()
#2 /app/web/wp/wp-admin/includes/image.php(276): wp_get_image_editor()
#3 /app/web/wp/wp-admin/includes/image.php(157): wp_create_image_subsizes()
#4 /app/web/wp/wp-admin/includes/ajax-actions.php(2452): wp_update_image_subsizes()
#5 /app/web/wp/wp-includes/class-wp-hook.php(288): wp_ajax_media_create_image_subsizes()
#6 /app/web/wp/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters()
#7 /app/web/wp/wp-includes/plugin.php(478): WP_Hook->do_action()
#8 /app/web/wp/wp-admin/admin-ajax.php(175): do_action()
#9 {main}
thrown in /app/web/wp/wp-includes/class-wp-image-editor-gd.php on line 96
[07-Mar-2020 09:50:08 UTC] [2020-03-07 09:50:08] ilab-media-tool.ERROR: [159] Uncaught Error: Call to undefined function imagecreatefromstring() in /app/web/wp/wp-includes/class-wp-image-editor-gd.php:96 Stack trace: #0 /app/web/app/plugins/ilab-media-tools/classes/Tools/Storage/StorageImageEditor.php(98): WP_Image_Editor_GD->load() #1 /app/web/wp/wp-includes/media.php(3189): ILAB\MediaCloud\Tools\Storage\StorageImageEditor->load() #2 /app/web/wp/wp-admin/includes/image.php(276): wp_get_image_editor() #3 /app/web/wp/wp-admin/includes/image.php(157): wp_create_image_subsizes() #4 /app/web/wp/wp-admin/includes/ajax-actions.php(2452): wp_update_image_subsizes() #5 /app/web/wp/wp-includes/class-wp-hook.php(288): wp_ajax_media_create_image_subsizes() #6 /app/web/wp/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters() #7 /app/web/wp/wp-includes/plugin.php(478): WP_Hook->do_action() #8 /app/web/wp/wp-admin/admin-ajax.php(175): do_action() #9 {main}   thrown {"file":"/app/web/wp/wp-includes/class-wp-image-editor-gd.php","line":96} []
```

**Server (please complete the following information)**
- Operating System: Heroku, php buildpack
- PHP Version: 7.4.3
- Web Server: nginx/1.16.1
- Using PHP-FPM? yes
- Using WordPress Cron? yes

**How did you install the plugin?**
Install via composer, https://github.com/cenobitedk/ktdf-site/tree/bedrock

**Comment by jawngee** [comment]
Do you not have GF or ImageMagick installed?

When WordPress load's Media Cloud's image editor class, Media Cloud image editor class actually will load either the ImageMagic editor or the GD editor depending on if ImageMagick is installed or not.

So it looks like you don't have either installed from the looks of it.

**Comment by cenobitedk** [comment]
Thanks, I didn't know GD was a requirement. 
I enabled it with this in the composer.json
```
{
    "require": {
        "ext-gd": "*"
    }
}
```
source: https://devcenter.heroku.com/articles/php-support#using-optional-extensions

And now it works perfectly! Thank you
