### ISSUE TITLE
Undefined array key "x-amz-bucket-region" after PHP 8 upgrade if region is not set to custom

### ISSUE THREAD

**Issue by Kiina** [Interfacelab/ilab-media-tools#141]
After upgrading from php 7.4 to 8.0 I can't activate the plugin anymore.

Full log:

```
Warning: Undefined array key "x-amz-bucket-region" in /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-aws/aws-sdk-php/src/S3/S3ClientTrait.php on line 219

Fatal error: Uncaught LogicException: Cannot change a fulfilled promise to rejected in /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/Promise.php:131 Stack trace: #0 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/Promise.php(119): MediaCloud\Vendor\GuzzleHttp\Promise\Promise->settle('rejected', Object(TypeError)) #1 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/Promise.php(213): MediaCloud\Vendor\GuzzleHttp\Promise\Promise->reject(Object(TypeError)) #2 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/Promise.php(157): MediaCloud\Vendor\GuzzleHttp\Promise\Promise::callHandler(1, Object(MediaCloud\Vendor\Aws\Result), Array) #3 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/TaskQueue.php(48): MediaCloud\Vendor\GuzzleHttp\Promise\Promise::MediaCloud\Vendor\GuzzleHttp\Promise\{closure}() #4 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): MediaCloud\Vendor\GuzzleHttp\Promise\TaskQueue->run() #5 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): MediaCloud\Vendor\GuzzleHttp\Handler\CurlMultiHandler->tick() #6 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/Promise.php(247): MediaCloud\Vendor\GuzzleHttp\Handler\CurlMultiHandler->execute(true) #7 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/Promise.php(224): MediaCloud\Vendor\GuzzleHttp\Promise\Promise->invokeWaitFn() #8 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/Promise.php(268): MediaCloud\Vendor\GuzzleHttp\Promise\Promise->waitIfPending() #9 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/Promise.php(226): MediaCloud\Vendor\GuzzleHttp\Promise\Promise->invokeWaitList() #10 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/Promise.php(63): MediaCloud\Vendor\GuzzleHttp\Promise\Promise->waitIfPending() #11 /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-aws/aws-sdk-php/src/S3/S3ClientTrait.php(199): MediaCloud\Vendor\GuzzleHttp\Promise\Promise->wait() #12 /var/www/html/wp-content/plugins/ilab-media-tools/classes/Tools/Storage/Driver/S3/S3Storage.php(318): MediaCloud\Vendor\Aws\S3\S3MultiRegionClient->determineBucketRegion('impulse') #13 /var/www/html/wp-content/plugins/ilab-media-tools/classes/Tools/Storage/Driver/S3/S3Storage.php(382): MediaCloud\Plugin\Tools\Storage\Driver\S3\S3Storage->getBucketRegion() #14 /var/www/html/wp-content/plugins/ilab-media-tools/classes/Tools/Storage/Driver/S3/S3Storage.php(452): MediaCloud\Plugin\Tools\Storage\Driver\S3\S3Storage->getS3Client(false, NULL) #15 /var/www/html/wp-content/plugins/ilab-media-tools/classes/Tools/Storage/Driver/S3/S3Storage.php(62): MediaCloud\Plugin\Tools\Storage\Driver\S3\S3Storage->getClient(NULL) #16 /var/www/html/wp-content/plugins/ilab-media-tools/classes/Tools/Storage/StorageToolSettings.php(560): MediaCloud\Plugin\Tools\Storage\Driver\S3\S3Storage->__construct() #17 /var/www/html/wp-content/plugins/ilab-media-tools/classes/Tools/Storage/StorageTool.php(125): MediaCloud\Plugin\Tools\Storage\StorageToolSettings::storageInstance() #18 /var/www/html/wp-content/plugins/ilab-media-tools/classes/Tools/ToolsManager.php(113): MediaCloud\Plugin\Tools\Storage\StorageTool->__construct('storage', Array, Object(MediaCloud\Plugin\Tools\ToolsManager)) #19 /var/www/html/wp-content/plugins/ilab-media-tools/classes/Tools/ToolsManager.php(291): MediaCloud\Plugin\Tools\ToolsManager->__construct() #20 /var/www/html/wp-content/plugins/ilab-media-tools/classes/Tools/ToolsManager.php(341): MediaCloud\Plugin\Tools\ToolsManager::instance() #21 /var/www/html/wp-content/plugins/ilab-media-tools/ilab-media-tools.php(198): MediaCloud\Plugin\Tools\ToolsManager::Boot() #22 /var/www/html/wp-includes/class-wp-hook.php(292): {closure}('') #23 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #24 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #25 /var/www/html/wp-settings.php(423): do_action('plugins_loaded') #26 /var/www/html/wp-config.php(96): require_once('/var/www/html/w...') #27 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...') #28 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...') #29 {main} thrown in /var/www/html/wp-content/plugins/ilab-media-tools/lib/mcloud-guzzlehttp/promises/src/Promise.php on line 131
```

Running php:8-fpm-alpine and nginx:mainline-alpine

No other plugins active.

I'm connecting to my own minio bucket.

When I set the region to custom and set `us-east-1` it works, but with php 7 it works on automatic and it's kinda hard to change the bucket region when you can't even activate the plugin without downgrading the php version first.

I think there is an issue with the `MediaCloud\Vendor\Aws\S3\S3MultiRegionClient->determineBucketRegion('impulse')` part.

**Comment by gallo2000sv** [comment]
updating the plugin causes this error as well. 
PHP Notice:  Undefined index: x-amz-bucket-region in /home/******g***l/wp-content/plugins/ilab-media-tools/lib/mcloud-aws/aws-sdk-php/src/S3/S3ClientTrait.php on line 219

**Comment by visamgultekin** [comment]
Do we not have a solution for this, yet?
